// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czasfggorygcsrecnzsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6YXNmZ2dvcnlnY3NyZWNuenNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODM0MjksImV4cCI6MjA1OTE1OTQyOX0.gAikrBkflp--ALhUhf1UqamDzyTq6pvxPGrcIPlWbmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);